const adminSupport = [
  "Active Listening",
  "Administrative Support",
  "APAC",
  "Apache Click",
  "Appointment Setting",
  "Article Submission",
  "Auctiva",
  "Behavioral Event Interviewing",
  "Belle Nuit Subtitler",
  "BGL Simple Fund",
  "Bitrix Intranet",
  "Blitz BASIC",
  "BPO Call Center",
  "BPO IT services",
  "Buildium",
  "Calendar Management",
  "Call Center Skills",
  "Chat Support",
  "Christian theology",
  "Clear Books",
  "Clerical Skills",
  "Collection Agencies",
  "Complaint Management",
  "Comptuer Maintenance",
  "Computer Repair",
  "Conflict Resolution",
  "Content Moderation",
  "Craigslist",
  "Customer Service",
  "Customer support",
  "Data Backup",
  "Data Center Operations",
  "Data Encoding",
  "Data Recovery",
  "Data Sheet Writing",
  "DataLife Engine",
  "Document Control",
  "Document Conversion",
  "DSL Troubleshooting",
  "eBay Listing/Writing",
  "eBay Motors",
  "Edufire",
  "Email Etiquette",
  "Email Handling",
  "Email Technical Support",
  "ERDAS IMAGINE",
  "Etsy Administration",
  "Event Planning",
  "Express Scribe",
  "Eyeon Fusion",
  "Fax",
  "Filing",
  "General Office Skills",
  "Google Docs",
  "Google Reader",
  "Google search",
  "GoToMyPC",
  "Grasshopper Virtual Phone",
  "Hardware Prototyping",
  "Helpdesk",
  "hi5",
  "Internet Research",
  "Interprise Suite ERP",
  "Interviewing",
  "Invoicing",
  "Keyboarding",
  "LibreOffice",
  "LivePerson",
  "Mail Merge",
  "Master Production Schedule",
  "Medical Billing and Coding",
  "Medical Informatics",
  "Medical Records Research",
  "Medical Transcription",
  "Microsoft MapPoint",
  "Microsoft Office",
  " Microsoft OneNote",
  "Microsoft Outlook",
  "Mind Mapping",
  "MoonScript",
  "Online Help",
  "OpenOffice",
  "OpenText",
  "OpenType",
  "Order Entry",
  "Order Processing",
  "PDF Conversion",
  "Phone Support",
  "Pomodoro Technique",
  "QHSE",
  "Real Estate Appraisal",
  "Receptionist Skills",
  "Research",
  "SAP Manufacturing Execution",
  "SAP2000",
  "Service Level Management",
  "Simple DirectMedia Layer",
  "SnagIt",
  "Sparx Systems Enterprise Architect",
  "Spine JS",
  "Spreadsheets",
  "Stereoscopy",
  "Stress Management",
  "Supervisory Skills",
  "Tally .ERP",
  "Tally Shoper",
  "Tealeaf cxImpact",
  " Technical Support",
  "Telephone Skills",
  "Time Management",
  "Transcription",
  "Travel Agent",
  "Travel Planning",
  "TSR",
  "Turbo C",
  "Typing",
  "U.S. Culture",
  "Video Upload",
  "Virtual Assistant",
  "VLookup Tables",
  "Wave Accounting",
  "Windows Media Connect",
  "Wordfast",
  "Zendesk",
];

const apiSiteFramework = [
  ".onion",
  "a-ads.com",
  "adbit.co",
  "Airbitz",
  "Armory",
  "AsMoney",
  "autotip.io",
  "bee-ads.com",
  "Binance",
  "Bitcoin/Altcoin Cloning",
  "Bitcoin/Altcoin Dice Game",
  "Bitcoin/Altcoin Gaming",
  "bitcoind",
  "Bitcoinj",
  "BitcoinLib",
  "BitcoinQT",
  " Bitcointalk.org",
  "Bitfinex",
  "Bitgigs.com",
  "Bitgo",
  "BitKit",
  "BitLendingClub",
  "BitLocker",
  "bitmedia.io",
  "BitMex",
  "Bitpay",
  "bitrated.com",
  "Bitstamp",
  "Bittask.com",
  "Bittrex",
  "Bleutrade",
  "Block.io",
  " Blockchain Receive Payments API",
  "Blockchain.info",
  "Blockcypher",
  "Blockonomics",
  "Blockonomics API",
  "Blockr.io",
  "Blockstrap",
  "BlockTrail",
  "breadwallet",
  "Btc-e",
  "BTCChina",
  "Btcjam",
  "Bter",
  "C-CEX",
  "cex.io",
  "cgminer",
  "Chain.com",
  "ChangeTip",
  "Circle.com",
  "Coin Faucet",
  "coin.mx",
  "coinad.com",
  "Coinality",
  "Coinapult",
  "Coinb.in",
  "Coinbase",
  "Coindesk",
  "Coinkite",
  "Coinmap",
  "CoinMarketCap",
  "CoinMarketCap API",
  "CoinPayments.net",
  "Coins-e",
  "coinurl.com",
  "Coinwarz",
  "cold storage",
  "cold wallet",
  "Copay",
  "Counterparty",
  "cpuminer",
  "Crypto Trading",
  "Cryptocoincharts",
  "CryptoCoinJS",
  "Cryptocurrency",
  " Cryptocurrency Exchange",
  "Cryptocurrency Exchange API",
  "Cryptocurrency Mining",
  "Cryptonator.com",
  "Cryptotrader",
  "Cryptsy",
  "DAO",
  "Darknet",
  "Electrum",
  "EOS",
  "Eternum",
  "Ethereum",
  "FaucetBox API",
  "getgems.org",
  "GreenAddress",
  "Havelock Investments",
  "Helloblock.io",
  "Hive",
  "hot wallet",
  "Huobi",
  " HW.1",
  "ICO",
  "Knc Wallet",
  "Kraken",
  "Kryptokit",
  "Ledger Wallet",
  "liqui.io",
  "LISK",
  "Litecoin",
  "localbitcoins",
  " Mastercoin / Omni wallet",
  "Masterxchange",
  "mellowads.com",
  "Michelson (Tezos)",
  "MoneyPot",
  "MoneyPot API",
  "ms-brainwallet",
  "mSIGNA",
  "Multibit",
  "Multisig",
  "MyBWALLET.com",
  "Mycelium",
  "Mycelium Gear",
  "NEO (AntShares)",
  "Neuroware",
  "newsBTC.com",
  "OKCoin",
  "P2SH",
  "Pi Wallet",
  "Poloniex",
  "purse.io",
  "Reddit /r/Bitcoin",
  "Ripple",
  "Schildbach wallet",
  "ShapeShift.io",
  "Solidity",
  "Steemit",
  "Stellar",
  "Stratum",
  "streamium",
  "Swisscex",
  "Tor",
  "Tradewave",
  "TradingView",
  "Trezor",
  "Tron",
  "UpHold API",
  "Vircurex",
  "wallet",
  "Wirex",
  "Xapo",
  "ZapChain",
];

const designMultimedia = [
  "2D Animation",
  "2D Design",
  "2D Modelling",
  "2D Rigging",
  "3D",
  "3D Animation",
  "3D Design",
  "3D Modeling",
  "3D Modelling",
  "3D Rendering",
  "3D Rigging",
  "3ds Max",
  "4D",
  "Abaqus",
  "Ableton Live",
  "Absynth",
  "ACDSee",
  "ACID Pro",
  "Acrylic Painting",
  "ActionScript",
  "Adobe Acrobat",
  "Adobe After Effects",
  "Adobe After Effects CS5",
  "Adobe Audition",
  "Adobe Captivate",
  "Adobe Contribute",
  "Adobe Creative Suite",
  "Adobe CS5",
  "Adobe Digital Marketing Suite",
  "Adobe Dreamweaver",
  "Adobe Dreamweaver CS5",
  "Adobe eLearning Suite",
  "Adobe Encore",
  "Adobe Fireworks",
  "Adobe Flash",
  "Adobe Flash CS5",
  "Adobe FrameMaker",
  "Adobe Freehand",
  "Adobe Illustrator",
  "Adobe Illustrator CS6",
  "Adobe Imageready",
  "Adobe InDesign",
  "Adobe InDesign CS6",
  "Adobe Insight",
  "Adobe LiveCycle",
  "Adobe LiveCycle Designer",
  "Adobe PageMaker",
  "Adobe Photoshop",
  "Adobe Photoshop CS6",
  "Adobe Photoshop Lightroom",
  "Adobe Premiere",
  "Adobe Premiere Elements",
  "Adobe Premiere Pro",
  "Adobe Soundbooth",
  "Advertisement Design",
  "After Effects",
  "AfterBurn",
  "AGAL",
  "Album Cover Design",
  "Alibre Design",
  "Alternative3D",
  "Animated Banner (gif)",
  "Animation",
  "Anime Studio",
  "Antenna Design",
  "Apple iMovie",
  "Apple Motion",
  "Architectural Rendering",
  "Art Direction",
  "Articulate",
  "Articulate Engage",
  "Articulate Presenter",
  "Articulate Studio",
  "ArtiosCAD",
  "Artlantis Render",
  "Artlantis Studio",
  "ArtRage",
  "Arts & Crafts",
  "ASIO",
  "Aspen HYSYS",
  "Audacity",
  "Audio Design",
  "Audio Editing",
  "Audio Engineering",
  " Audio Mastering",
  "Audio Mixing",
  "Audio Post Production",
  "Audio Production",
  "Audio Restoration",
  "Audio Services",
  "Autodesk 3D Studio Max",
  "Autodesk Architecture",
  "Autodesk Autocad Civil3D",
  "Autodesk Maya",
  "Autodesk Mudbox",
  "Autodesk Navisworks",
  "Autodesk Revit",
  "Autodesk Sketchbook Pro",
  "Autodesk Softimage",
  "Autodys AcceliCAD",
  "AVEVA PDMS",
  "Avid",
  "Avid Pro Tools",
  "Away3D",
  "Axure RP",
  "Banner Ad Design",
  "Banner Ads",
  "Banner Design",
  "Bassoon",
  "Bentley Microstation",
  "BeOS",
  "Blender3D",
  "Blog Design",
  "Blog Development",
  "Book Cover Design",
  "Bootstrap",
  "Brochure Design",
  "Building Architecture",
  "Building Regulations",
  "Business Card Design",
  "Business Cards",
  "CAD/CAM",
  "Cadence Platform",
  "Cakewalk Sonar",
  "Calligraphy",
  "Camtasia",
  "Capture NX2",
  "Caricature & Cartoons",
  "Caricature Drawing",
  "Cartooning",
  "Celemony Melodyne",
  "CG Artwork",
  "CGI",
  "Chaos Group V-Ray",
  "Character Design",
  "Chroma key",
  "Cinematography",
  "Comic Art",
  "Commercials",
  "Compositing",
  " Computer Graphics",
  "Computer Hardware Design",
  "COMSOL Multiphysics",
  "Concept Artistry",
  "Concept Design",
  "Concept Software InPage",
  "Corel Paint Shop Pro",
  "Corel Painter",
  "Corel Ventura",
  "CorelDraw",
  "Corporate Identity",
  "Cover Design",
  "Covers & Packaging",
  "CPU Design",
  "Creative Design",
  "CSS",
  "CSS3",
  "CUDA",
  "Dancing",
  "DaVinci Resolve",
  "Desktop Publishing",
  "Digital Painting",
  "Digital Photography",
  "Digital scrapbooking",
  "Digital Sculpting",
  "DJing",
  "Drafting",
  "Drawing",
  "Dreamweaver",
  "Drums",
  "DVD Mastering",
  "DVD Studio Pro",
  "Eagle",
  "Electrical Drawing",
  "Electronic Workbench",
  "Embroidery",
  "Embroidery Digitization",
  "Engineering drawing",
  "ETABS",
  "Evolus Pencil",
  "Fashion Design",
  "Fashion Modeling",
  "FFmpeg",
  "Film Direction",
  "Film Dubbing",
  "Film Production",
  "Final Cut Pro",
  "Final Cut Pro X",
  "Finale / Sibelius",
  "Fire Protection Engineering",
  "FL Studio",
  "Flash",
  "Flash 3D",
  "Flex",
  "Flyer Design",
  "Font Development",
  "FontForge",
  "Format & Layout",
  "FreeCad",
  "Furniture Design",
  "GarageBand",
  "Gemvision ClayTrix",
  "Gemvision Matrix",
  "Geometry",
  "GIMP",
  "Google SketchUp",
  "Graphic Design",
  "Greenline VeriFIX",
  "GUI Design",
  "Guitar Composition",
  "Guitar Performance",
  "headus UVLayout",
  "Houdini",
  "HTML/CSS banner design",
  "HVAC System Design",
  "IClone",
  "Icon Design",
  "Illustration",
  "Illustrator",
  "Image Editing",
  "Image Processing",
  "InDesign",
  "Industrial Design",
  "Infographics",
  "Information design",
  "Inkscape",
  "Instructional design",
  "Interactive Voice Response",
  "Interior Design",
  "Invitation Design",
  "iPad UI Design",
  "iPhone UI design",
  "ITK",
  "JDF",
  "Jewelry Design",
  "Jig and Fixture Design",
  "Jingle Program Production",
  "Job Definition Format (JDF)",
  "Kerkythea",
  "Keynote",
  "KitchenDraw",
  "Label and Package Design",
  "Landing Pages",
  "Landscape Design",
  "Laser Engraving",
  "Lectora",
  "Lightwave 3d",
  "Lightworks",
  "Logic Pro",
  "Logo Design",
  "Machine Design",
  "Magazine Layout",
  "Magic Bullet Colorista",
  "Magic Bullet Looks",
  "Makerbot",
  "Maple",
  "Mastercam",
  "Max",
  "Maxon BodyPaint 3D",
  "Maxon Cinema 4D",
  "Maya",
  "Medical Illustration",
  "Microcontroller Programming",
  "Microsoft Expression Studio",
  "Microsoft PowerPoint",
  "Microsoft Publisher",
  "Microsoft Sharepoint Administration",
  "Microsoft Visio",
  "Microsoft Windows Movie Maker",
  "Microsoft Windows Template Library",
  "Microstock Photography",
  "Microstration v8",
  "MIDI",
  "mobi",
  "Model Sheet Design",
  "Motion Graphics",
  "MPD",
  "Murals",
  "Music",
  "Music Arrangement",
  "Music Dubbing",
  "Music engraving",
  "Music Producing",
  "Musical composition",
  "Navigation System Design",
  "Next Limit Maxwell Render",
  "Next Limit RealFlow",
  "Non-linear editing system",
  "Nuendo",
  "Nuke",
  "NVIDIA Mental Ray",
  "Oil painting",
  "OpenGL",
  "Oracle Complex Events Processing",
  "P-CAD",
  "Packaging Design",
  "Page Layout",
  "Paint.NET",
  "Panoramic Stitching",
  "Papercraft",
  "ParticleIllusion",
  "PESTEL",
  "Photo Editing",
  "Photo Manipulation",
  "Photograph Color Correction",
  "Photography",
  "PhotoScape",
  "Photoshop",
  "Photoshop Coding",
  "Photoshop Design",
  "Piano Composition",
  "Piano Performance",
  "Pinnacle Studio",
  "Pixologic ZBrush",
  "Polymer Clay Sculpting",
  "Portrait Painting",
  "Poser",
  "Post-Production",
  "Poster Design",
  "Pre-production",
  "Prepress",
  "Presentation Design",
  "Presentations",
  "PreSonus Studio One",
  "Prezi",
  "Print",
  "Print design",
  "Print Layout Design",
  "Product Development",
  "Propellerhead Reason",
  "ProTools",
  "PSD to HTML",
  "PSD2CMS",
  "PSPICE",
  "Punch Home Design Studio Pro",
  "QS Cad",
  "Quark Xpress",
  "QuarkXPress",
  "Quartz Composer",
  "Radiant Zemax",
  "Radio Broadcasting",
  "Radio personality",
  "Realist Painting",
  "RhinoScript",
  "Robotscope",
  "RWD",
  "SAI",
  "Scale Modeling",
  "Sculpting",
  "Sencha Architect",
  "SensAble ClayTrix",
  "Sequential Art",
  "Shopify Templates",
  "Sibelius",
  "Siemens NX",
  "Singing",
  "Sketching",
  "SketchUp",
  "Solid Edge",
  "Sony Vegas",
  "Sound Design",
  "Sound Editing",
  "Sound Effects",
  "Sound Forge",
  "Soundtrack Pro",
  "Spacewalk",
  "Special Purpose Machines Design",
  "Spiral Graphics Genetica",
  "STAAD",
  "Standard Template Library (STL)",
  "Stationery Design",
  "Steinberg Cubase",
  "Steinberg WaveLab",
  "Sticker Design",
  "Still Life Painting",
  "Storyboarding",
  "Style Guide Development",
  "Synthetic Aperture Color Finesse",
  "T-Shirt Design",
  "T-Shirts",
  "Tekla Structures",
  "Templates",
  "Texture Artist",
  "The Foundry NUKE",
  "The Pixel Farm PFTrack",
  "Toon Boom Harmony",
  "Toon Boom Studio",
  "Trade Show Exhibition Design",
  "TVPaint",
  "Typesetting",
  "Typography",
  "UI Design",
  "Ulead COOL 3D",
  "Ulead VideoStudio",
  "Unity 3D",
  "Urban Design",
  "User Experience Design",
  "User Interface Design",
  " UV Mapping",
  "V-Ray",
  "VFX Animation",
  "VFX Design",
  "Video Broadcasting",
  "Video Conversion",
  "Video Editing",
  "Video Post Editing",
  "Video Production",
  "Video Publishing",
  "Video Ripping",
  "Video Services",
  "Videography",
  "VIDVOX VDMX",
  "Violin Composition",
  "Violin Performance",
  "Violoncello",
  "Visual Arts",
  "Visual Merchandising",
  "Voice Acting",
  "Voice Over",
  "Voice Over (man)",
  "Voice Over (woman)",
  "Voice Talent",
  "Watercolor Painting",
  "Web Design",
  "Website Design",
  "Wilcom Embroidery Digitization",
  "Wilcom EmbroideryStudio",
  "Wind Power Consulting",
  "Wireframing",
  "Word",
  "WordPress Themes",
  "Xara Xtreme",
  "Yahoo! Store Design",
];

const hardwareEngineering = [
  "3D Printing",
  "3D Scanning",
  "3D Systems",
  "3GSM",
  "ACPI",
  "Adaptive Algorithms",
  "Altium Designer",
  "Amplifiers and Filters",
  "Analog Electronics",
  "ANSYS",
  "ArchiCAD",
  "Architecture",
  "ArcScene",
  "Arduino",
  "AS400",
  "Astrophysics",
  "AutoCAD",
  "AutoCAD 2012",
  "Autodesk",
  "Autodesk Inventor",
  "Biology",
  "Biotechnology",
  "Bluetooth",
  "Broadcast Engineering",
  "CATIA",
  "CDMA",
  "Chemical Engineering",
  "Circuit Design",
  "Cisco",
  "Civil Engineering",
  "Clean Technology",
  "Climate Sciences",
  "Computer Aided Manufacturing (CAM)",
  "Computer Engineering",
  "Computer-Aided Design",
  "Construction Monitoring",
  "COSMO-RS Chemical Engineering",
  "Digital Electronics",
  "Digital Engineering",
  " Digital Signal Processing",
  "Drones",
  "EDGE",
  "Electrical Engineering",
  "Electronic Design",
  "Electronics",
  "Embedded Software",
  "Embedded Systems",
  "Engineering Design",
  "Fiber Optics",
  "Finite Element Analysis",
  "Form-Z",
  "Game Consoles",
  "Genetic Engineering",
  "Geographic Information System (GIS)",
  "Geology",
  "Geomagic",
  "Geomagic Design X",
  "Geospatial",
  "GPGPU",
  "GPS Development",
  "Home Design",
  "Human Sciences",
  "Imaging",
  "Industrial Engineering",
  "Instrumentation",
  "Integrated Circuits",
  "ISO 9001",
  "Kaizen",
  "Kinect",
  "LabVIEW",
  "LabWindows/CVI",
  "Lean Consulting",
  "Linear Programming",
  "Logistics & Shipping",
  "Manufacturing Design",
  "Materials Engineering",
  "MathCAD",
  "Mathematics",
  "Mechanical Design",
  "Mechanical Engineering",
  "Mechatronics",
  "Microcontroller",
  "Microstation",
  " Mining Engineering",
  "Nanotechnology",
  "Neshlab",
  "Netfabb",
  "Nextengine",
  "OrCAD",
  "PCB Design",
  "Petroleum Engineering",
  "Physics",
  "PLC & SCADA",
  "Pro-E",
  "Product Design",
  "Project Scheduling",
  "PTC Creo Elements/Pro",
  "Quantum",
  "Rapid Prototyping",
  "RapidWorks",
  "Rasperry Pi",
  "Remote Sensing",
  "RepRap",
  "Rhinoceros 3D",
  "Robotics",
  "RTOS",
  "Scientific Computation",
  "Scientific Research",
  "SketchUp Pro",
  "SolidWorks",
  "Stratasys",
  "Structural Engineering",
  "Telecommunications Engineering",
  "Textile Engineering",
  "USB Electronics",
  "Vectorworks",
  "Verilog / VHDL",
  "VLSI",
  "Wi-Fi",
  "WiMAX",
  "Wireless Network Implementation",
];

const legalities = [
  "Alternative Dispute Resolution",
  "Antitrust",
  "Arbitration",
  "Bankruptcy",
  "Benefits Law",
  "BitLicense",
  "Civil Law",
  "Commercial Lending",
  "Compensation",
  "Consumer Protection",
  "Contract Drafting",
  "Contract Law",
  "Copyright",
  "Corporate Law",
  "Corporate Taxes",
  "Criminal Law",
  "Employment Law",
  "Environmental Law",
  "Family Law",
  "Fraud Analysis",
  "Immigration Law",
  "Insurance Consulting",
  "Intellectual Property Law",
  "International Law",
  "International taxation",
  "Legal Consulting",
  "Legal Research",
  "Legal Transcription",
  "LexisNexis Accurint",
  "LexisNexis Practice Advisor",
  "Licensing",
  "Litigation",
  "Medical Law",
  "Non-disclosure Agreements",
  "Notary public",
  "Paralegal Services",
  "Patent Law",
  "Privacy",
  "Real Estate Law",
  "Records Management",
  "Tax Law",
  "Trade Law",
  "Trademark Consulting",
  "Trusts Estates and Wills",
  "Westlaw",
];

const management = [
  "Accounting",
  "AccountMate",
  "Accounts Payable Management",
  "Accounts Receivable Management",
  "Acquisitions",
  "Adaco",
  "Adobe Analytics",
  "Archibus",
  "Arriba",
  "Artiva",
  "Auditing",
  "Bank Reconciliation",
  "Bookkeeping",
  "Brand Licensing",
  "Budgeting & Forecasting",
  "Building Estimation",
  "Business Activity Monitoring",
  "Business Analysis",
  "Business Coaching",
  "Business Continuity Planning",
  "Business Development",
  "Business intelligence",
  "Business IT Alignment",
  "Business Management",
  "Business Mathematics",
  "Business Modeling",
  "Business Planning",
  "Business Process Modeling",
  "Business Process Reengineering",
  "Business Scenario Development",
  "Business Valuation",
  "Calculus",
  "Cognos",
  "Compliance",
  "Corporate Finance",
  "Corporate Strategy",
  "Cost accounting",
  "Data Interpretation",
  "Data Sufficiency",
  "DMAIC",
  "Driving",
  "Economics",
  "Enterprise Resource Planning (ERP)",
  "Entrepreneurship",
  "Event Management",
  "Financial Accounting",
  "Financial Analysis",
  "Financial Forecasting",
  "Financial Management",
  "Financial modeling",
  "Financial Prospectus Writing",
  "Financial Reporting",
  "Financial Statements",
  "Franchise Consulting",
  "Fraud Mitigation",
  "Fundraising",
  "GAAP",
  "Hospitality",
  "HR Benefits",
  "Human Resource Information Systems",
  "Human Resource Management",
  "IBM Lotus Notes Traveler",
  "IBM Lotus Symphony",
  "IBM SameTime",
  "IdeaBlade DevForce",
  "Internal Auditing",
  "Intuit Lacerte Tax",
  "Intuit QuickBooks",
  "Intuit Quicken",
  "Inventory Management",
  "Investment Research",
  "IRM Income Tax Audits",
  "ISO 9000",
  "ITIL",
  "Job Costing",
  "Job Description Writing",
  "LinkedIn Recruiting",
  "Magic Tricks",
  "Management Development",
  "Meego Development",
  "Microsoft Excel",
  "Microsoft Excel PowerPivot",
  "Microsoft Project",
  "MLS Consulting",
  "Multi-Criteria Decision Analysis",
  "MYOB Administration",
  "Negotiation",
  "Operations Management",
  "Oracle Universal Content Management",
  "OrangeCRM",
  "Organizational Behavior",
  "Organizational Development",
  "Payroll Processing",
  "Peachtree Accounting",
  "Personal Development",
  "Process architecture",
  "Process improvement",
  "Program Management",
  "Project Management",
  "Project Management Professional",
  "Project Planning",
  "Property Development",
  "Property Management",
  "Property Tax",
  "Purchasing Management",
  "Quantity Surveying",
  "Recruiter",
  "Recruiting",
  "Risk Management",
  "Sage ERP Accpac",
  "SAP Business Objects",
  "SAP Crystal Reports",
  "Sassu",
  "SiteScope",
  "Six Sigma",
  "Startup Consulting",
  "Statistics",
  "Statpoint Statgraphics",
  "Stock Management",
  "Strategic Planning",
  "Supply Chain Management",
  "Tax Preparation",
  "Teaching Mathematics",
  "Technical Recruiter",
  "TIBCO ActiveMatrix BusinessWorks",
  "Underwriting",
  "Venture Capital Consulting",
  "Virtual storage access method (VSAM)",
  "Workforce Management",
  "Workshop Facilities",
  "Xerox",
];

const marketing = [
  "Account Management",
  "ACT!",
  "Ad Planning & Buying",
  "Ad Posting",
  "Ad Servers",
  "Advertising",
  "Affiliate Marketing",
  "Amazon Ads",
  "App Store Optimization (ASO)",
  "Automated Call Distribution",
  "AWeber",
  "B2B Marketing",
  "Bing Ads",
  "Brand Ambassador",
  "Brand Consulting",
  "Broadcast Advertising",
  "BroadVision ClearVale",
  "BroadVision QuickSilver",
  "Brochures",
  "Bulk Marketing",
  "Classifieds Posting",
  "Common Language Runtime",
  "Constant Contact",
  "Corporate Brand Identity",
  "Cost Per Thousand Advertising (CPM)",
  "CRM",
  "DELFTship",
  "Direct Marketing",
  "Display Ads",
  "eBay",
  "eBay Marketing",
  "Electronic funds transfer",
  "Eloqua",
  "Email Marketing",
  "ExactTarget",
  "Facebook Marketing",
  "Five9",
  "Freelance Marketing",
  "Google AdSense",
  "Google AdWords",
  "Google Places API",
  "Google Search API",
  "Google Webmaster Central",
  "Google Website Optimizer",
  "Google+",
  "Google+ Marketing",
  "Growth hacking",
  "HootSuite",
  "In-Game Advertising",
  "Inbound Marketing",
  "Indexing",
  "Instagram Marketing",
  "Internet Marketing",
  "Internet Surveys",
  "ISEB",
  "Lead Generation",
  " Link Wheel",
  "Loyalty Marketing",
  "MailChimp / Mandrill",
  "Market Research",
  "Marketing",
  "Marketing Strategy",
  "Media Buying",
  "Media Relations",
  "Microsoft adCenter",
  "Microsoft Windows Media Connect",
  " Mobile Advertising",
  "Motivational Speaking",
  "Multi Level Marketing (MLM)",
  " MySpace Marketing",
  "Ning Marketing",
  "Off-page Optimization",
  "Online Community Management",
  "OpenACS",
  "Outbound Sales",
  "Pay Per Click Advertising",
  "Pay Per Click Advertising (PPC)",
  "Pinterest Marketing",
  "Press Advertising",
  "Press Release Distribution",
  "Print Advertising",
  "Public Relations",
  "Public Speaking",
  "Quick Sales System",
  "Reputation Management",
  "Retail Merchandising",
  "Retail Ops Management",
  "Retail Sales Management",
  "Salary Surveys",
  "Sales",
  "Sales Management",
  "Sales Promotion",
  "Salesforce.com",
  "Salesgenie.com",
  "SASSIE Mystery Shopping",
  "ScrapeBox",
  "Search Engine Marketing (SEM)",
  "Search Engine Optimization (SEO)",
  "Selling",
  "SENuke X",
  "SEO Keyword Research",
  "SEOMoz",
  "Social Media Manager",
  "Social Media Marketing",
  "Social Media Optimization (SMO)",
  "Social Network Administration",
  "StrongMail",
  "Supervised learning",
  "Survey Design",
  "SurveyMonkey",
  "Telemarketing",
  "Toktumi",
  "Trade Marketing",
  "Traffic Geyser",
  "TSM Administration",
  "TV Broadcasting",
  "Twitter Marketing",
  "vBSEO",
  "Viral Marketing",
  "Web Analytics",
  "Website Analytics",
  "Word-of-Mouth",
  "Worldbuilding",
  "Wrap Advertising",
  "XRumer",
  "Yahoo! Advertising Solutions",
  "Yahoo! Search Marketing",
  "Yandex API",
  "Yandex MatrixNet",
  "YouTube Marketing",
  "Zillow Marketing",
];

const methodology = [
  "Agile",
  "Analytics",
  "CMS",
  "Debugging",
  "Face Recognition",
  "Game Design",
  "Gamification",
  "Link Building",
  "Map Reduce",
  "MMORPG",
  "MVC",
  "OCR",
  "Pattern Matching",
  "Scrum",
  "SEO",
  "Social Engine",
  "Social Networking",
  "Software Architecture",
  "Software Development",
  "Software Testing",
  "UML Design",
  "Usability Testing",
  "Virtual Worlds",
  "Web Scraping",
  "Website Testing",
];

const mobilePhone = [
  "Amazon Kindle",
  "Blackberry",
  "Energizer",
  "Huawei",
  "HTC",
  "iPad",
  "iPhone",
  "Mobile Phone",
  "Motorola",
  "Nokia",
  "Palm",
  "Samsung",
];

const networkSecurity = [
  "Anti-Virus",
  "Check Point",
  " Cisco Certified Entry Networking Technician (CCENT)",
  "Cisco Certified Network Associate (CCNA)",
  "CloudFlare",
  "Firewall",
  "Hacking",
  " HTTP proxy",
  "Internet Security",
  "InterPlanetary File System (IPFS)",
  "Juniper",
  "Linux System Administration",
  "Malware",
  "Network Administration",
  "Network Engineering",
  "Network Programming",
  "Network Security",
  "Penetration Testing",
  "Reverse Engineering",
  "Security",
  "Security Analysis",
  "Security Engineering",
  "Security Infrastructure",
  "TCP/IP",
  "Virtual Network Computing (VNC)",
];

const programmingIt = [
  ".NET",
  ".NET Compact Framework",
  ".NET for Web",
  ".NET Framework",
  ".NET Remoting",
  "1ShoppingCart",
  "A/B Testing",
  "A2Billing",
  "Ab Initio",
  "ABAP",
  "AbleCommerce",
  "Abstract Window Toolkit (AWT)",
  "Acronis",
  "Actian",
  "ActiveCollab",
  "ActiveX",
  "Ada",
  "ADK",
  "ADO.NET",
  "ADO.NET Entity Framework",
  "Adobe Air",
  "Adobe Business Catalyst",
  "Adobe Flex",
  "Adobe GoLive",
  "Adobe Wallaby",
  "ADVA",
  "Agile software developmennt",
  "Aiki",
  "AIX",
  "AJAX",
  "Akamai",
  "Akelos",
  "Akka",
  "Alfresco development",
  "Alfresco user",
  "Algorithm Development",
  "Algorithms",
  "Alpha",
  "Amadeus",
  "Amanda Backup",
  "Amazon Appstore",
  "Amazon EC2",
  "Amazon MWS",
  "Amazon Relational Database Service",
  "Amazon S3",
  "amCharts",
  "aMember",
  "AMQP",
  "Android",
  "Android App Development",
  "Android Honeycomb",
  "Android SDK",
  "AngularJS",
  "Ani.js",
  "ANSI C",
  "Antispam and Antivirus",
  "Apache Administration",
  "Apache Ant",
  "Apache Avro",
  "Apache Camel",
  "Apache Cassandra",
  "Apache CloudStack",
  "Apache Cocoon",
  "Apache Cordova",
  "Apache CXF",
  "Apache Flume",
  "Apache Hive",
  "Apache Jakarta POI",
  "Apache Kafka",
  "Apache Mahout",
  "Apache Maven",
  "Apache Nutch",
  "Apache OFBiz",
  "Apache Shirol",
  "Apache Struts",
  "Apache Subversion (SVN)",
  "Apache Thrift",
  "Apache Tiles",
  "Apache Tomcat",
  "API Development",
  "API Documentation",
  "App Store",
  "App Usability Analysis",
  "App.js",
  "Appcelerator Titanium",
  "AppFuse",
  "Apple iWeb",
  "Apple iWork",
  "Apple UIKit Framework",
  "Apple WebObjects",
  "Apple Xcode",
  "AppleScript,",
  "Applicant Tracking Systems",
  "Application Lifecycle Management",
  "Application Server",
  "Arbor",
  "ARCserve",
  "ARM",
  "Artificial Intelligence",
  "Artificial Neural Networks",
  "Artisteer",
  "ash.MVC",
  "ASP",
  "ASP.NET",
  "ASP.NET MVC",
  "Asp.Net Storefront",
  "AspectJS",
  "Assembla",
  "Assembly",
  "Assembly Language",
  "Asynchronous I/O",
  "At.js",
  "ATL",
  "Atlas",
  "Atlassian Confluence",
  "Atlassian GreenHopper",
  "Atlassian JIRA",
  "ATM Implementation",
  "Atmel AVR",
  "Atom",
  "Augmented Reality",
  "Authorize.Net Development",
  "AutoHotKey",
  "AutoIt",
  "AutoLISP",
  "Automated Testing",
  "Automation",
  "Avactis",
  "Avaya",
  "AWK",
  "Axapta",
  "backbone.js",
  "Bacula",
  "Bada",
  "Balsamiq",
  "Basecamp",
  "Bash",
  "Bash shell scripting",
  "BASIC",
  "bbPress",
  "Behavior Driven Development (BDD)",
  "Betfair",
  "Big Data",
  "BigCommerce",
  "Bioinformatics",
  "Biostatistics",
  "BIRT",
  "BitBucket",
  "Bitrix",
  "BitRock Installbuilder",
  "BizTalk Server",
  "Black Box Testing",
  "Blackberry App Development",
  "Blackberry OS",
  "Blackboard",
  "BlazeDS",
  "Blogs",
  "blue.box",
  "Boba.js",
  "BoonEx Dolphin",
  "Boost",
  "Border Gateway Protocol",
  "Borland C++ Builder",
  "Borland SilkTest",
  "Bounce.js",
  "Box.net Development",
  "Box2D",
  "BPCS",
  "Brew",
  "BSD",
  "Bugzilla",
  "Business Process Execution Language (BPEL)",
  "C (Programming Language)",
  "C Shell",
  "C#",
  "C++",
  "Cache Management",
  "Cairngorm",
  "CakePHP",
  "Capistrano",
  "Carbide.c++",
  "Caspio Administration",
  "Caspio Programming",
  "Cavium Octeon Fusion",
  "Cavium OCTEON Plus MIPS64",
  "CCT",
  "CentOS",
  "Central Desktop Development",
  "Central Reservation Systems",
  "Centreon",
  "Certified Information Systems Security Professional (CISSP)",
  "Change Management",
  "Chart.js",
  "Chartist.js",
  "Chartkick",
  "Chrome Extension",
  "Chrome OS",
  "Chrome push notifications",
  "Cisco ASA",
  "Cisco CallManager",
  "Cisco Certified Design Associate (CCDA)",
  "Cisco Certified Design Expert (CCDE)",
  "Cisco Certified Design Professional (CCDP)",
  "Cisco Certified Network Professional (CCNP)",
  "Cisco IOS",
  "Cisco PIX",
  "Cisco Routers",
  "Citrix",
  "Citrix NetScaler",
  "Citrix XenServer",
  "CiviCRM",
  "ClamAV",
  "ClearQuest",
  "ClickBank",
  "Clojure",
  "Cloud security framework",
  "Cloudera",
  "CloudForge",
  "Cluster Computing",
  "CMS Commander",
  "CMS Development",
  "CNC Programming",
  "Cobol",
  "Cocoa",
  "Cocoa Touch",
  "Cocos2d",
  "Code Refactoring",
  "CodeIgniter",
  "CoDeSys",
  "CodeWarrior",
  "CoffeeScript",
  "ColdFusion",
  "CollabNet TeamForge",
  "Collaborative filtering",
  "COM (Component Object Model)",
  "Comet",
  "Compass CSS",
  "Compiler",
  "Component Object Model (Microsoft COM)",
  "Computational Linguistics",
  "Computer Assembly",
  "Computer Hardware Installation",
  "Computer Networking",
  "Computer vision",
  "Comsat",
  "ConceptShare Development",
  "Concrete5 CMS",
  "Construction",
  "Contao CMS",
  "Content Management System",
  "Continuous Integration",
  "Contour",
  "CORBA",
  "Core Java",
  "Corona",
  "Cosmos OS",
  "Cotonti",
  "CouchDB",
  "cPanel",
  "CppUnit",
  "CreateJS",
  "Cryptography",
  "CSU/DSU",
  "Cucumber",
  "cURL",
  "Custom CMS",
  "Customer Information Control System (CICS)",
  "Cut.js",
  "CVS",
  "D (Programming Language)",
  "D3.js",
  "Dart",
  "Data Analytics",
  "Data Cleansing",
  "Data Engineering",
  "Data Ingestion",
  "Data Logistics",
  "Data Mining",
  "Data Modeling",
  "Data Protection",
  "Data Science",
  "Data scraping",
  "Data Structures",
  "Data Warehousing",
  "Database Administration",
  "Database Caching",
  "Database design",
  "Database Management",
  "Database Modeling",
  "Database Programming",
  "Database Testing",
  "DB Administration",
  "DB2",
  "dBASE",
  "dBase Administration",
  "dBase Programming",
  "DBMS",
  "DCOM",
  "Debian",
  "Decentralized Applications (Dapps)",
  "Defect Tracking",
  "Delphi  Demandware",
  "Desktop Support",
  "DevExpress",
  "DevExpress Reporting",
  "Device Driver Development",
  "DevOps",
  "DHCP",
  "DHTML",
  "Digital Access Pass",
  "Digital Mapping",
  "Dimdim Development",
  "Directory Submission",
  "DirectShow",
  "DirectX",
  "Disaster recovery",
  "Distributed computing",
  "DIY",
  "Django",
  "DNSsec",
  "Doctrine ORM",
  "Dojo Toolkit",
  "Domain Migration",
  "DOS",
  "Draggabilly.js",
  "Drop Shipping",
  "Dropbox API",
  "Dropzone.js",
  "Drupal",
  "Drupal 7",
  "DTS",
  "Dundas Chart Controls",
  "Dwolla API",
  "E4X",
  "eBay API",
  "eBay Web Services",
  "Echo.js",
  "Eclipse",
  "ECMAscript",
  "eCommerce Consulting",
  "Econometrics",
  "EJS Chart",
  "Ekiga",
  "Ektron",
  "Elastix",
  "Electronic data interchange (EDI)",
  "Elgg",
  "Elixir",
  "Elliptic Curve Cryptography (ECC)",
  "Embedded C",
  "Embedded Linux",
  "Embedded System",
  "Ember Charts",
  "EmberJS",
  "EMC Symmetrix",
  "Encryption",
  "Enterprise JavaBeans (EJB)",
  "Epoch",
  "Erlang",
  "Erwin",
  "Essbase",
  "Eucalyptus Cloud",
  "EViews",
  "Exim",
  "Express JS",
  "Expression Engine",
  "Ext JS",
  "Extract",
  "eZ Components",
  "eZ Publish",
  "F#",
  "F5",
  "Facebook Development",
  "Facebook Games Development",
  "Facebook Javascript (FBJS)",
  "Facelets",
  "Fattalble.js",
  "FBML",
  "Fedora",
  "Fetchmail",
  "Field-Map",
  "Field-Programmable Gate Array (FPGA)",
  "FileMaker",
  "FileMaker Programming",
  "Firebird",
  "Firefox Plugin Development",
  "Flask",
  "Flesk",
  "Flot",
  "Flowcharts",
  "Flux.js",
  "Fn.js",
  "Forth",
  "Fortran",
  "Forum Development",
  "FourSquare Development",
  "FoxPro",
  "FoxPro Administration",
  "FoxPro Programming",
  "FreeBSD",
  "FreeMarker",
  "FreePBX",
  "Freeswitch",
  "Frontend Development",
  "FTP",
  "Fuel",
  "FUEL CMS",
  "Full-text Search Engines",
  "Functional Design",
  "Functional testing",
  "Fusebox",
  "Fusioncharts",
  "Fuzzing",
  "Game Development",
  "Game Programming",
  "Game Server",
  "Game Server Administration",
  "Game Server Setup",
  "Game Testing",
  "GameSalad Creator",
  "GDI",
  "Gearman",
  "GearTrax",
  "Genetic Algorithms",
  "Geolocation",
  "GetResponse",
  "Ggplot2",
  "Git",
  "GitHub",
  "GlassFish",
  "Glassware",
  "GLSL",
  "GNU Octave",
  "Go (Programming Language)",
  "GoLang",
  "GoldMine",
  "Google AdSense API",
  "Google AdWords Development",
  "Google Analytics API",
  "Google App Engine API",
  "Google Apps",
  "Google Apps API",
  "Google Calendar API",
  "Google Charts",
  "Google Docs API",
  "Google Gadgets",
  "Google Gadgets API",
  "Google Glass",
  "Google Glass SDK",
  "Google Go",
  "Google Map Maker",
  "Google Maps API",
  "Google Mirror API",
  "Google Play",
  "Google Reader API",
  "Google Sites Administration",
  "Google Sites API",
  "Google Spreadsheets API",
  "Google Swiffy",
  "Google Web Toolkit",
  "Google+ Development",
  "Gradle",
  "Grails",
  "Graph Databases",
  "Graphics Programming",
  "Greenplum",
  "Gremlins.js",
  "GridList.js",
  "Groovy",
  "GTK+",
  "Gumby",
  "HAML",
  "Hammerkit",
  "HAProxy",
  "Hardware Troubleshooting",
  "Haskell",
  "HaXe",
  "Hbase",
  "Heroku",
  "Hibernate",
  "Highcharts",
  "Highwire",
  "Home Automation",
  "Honeycomb",
  "Horde",
  "HP Cloud",
  "HP Network Management Center (HPNMC)",
  "HP Quality Center",
  "HP QuickTest Professional (HPQTP)",
  "HP-UX",
  "HTML",
  "HTML5",
  "IBATIS",
  "IBM AS/400 Control Language",
  "IBM DB2 Administration",
  "IBM DB2 Programming",
  "IBM InfoSphere DataStage",
  "IBM Lotus Domino",
  "IBM PowerPC Programming",
  "IBM Rational Rose",
  "IBM SmartCloud",
  "IBM SPSS",
  "IBM System p",
  "IBM System Storage",
  "IBM System x",
  "IBM Tivoli Framework",
  "IBM Watson",
  "IBM WebSphere",
  "IBM z/VM Administration",
  "ICD Coding",
  "Ice Cream Sandwich",
  "Icefaces",
  "Icinga",
  "IContact",
  "IDRISI",
  "IMacros",
  "IMS",
  "Informatica",
  "Information Architecture",
  "Information Builders WebFOCUS",
  "Information Management",
  "Informatique",
  "Informix Administration",
  "Informix Programming",
  "Infragistics",
  "Infusionsoft Administration",
  "Infusionsoft Development",
  "Ingress",
  "Ingress Filtering",
  "Inno Setup",
  "Installer Development",
  "InstallShield",
  "InstantClick.js",
  "IntelliCred",
  "IntelliJ IDEA",
  "Interaction design",
  "InterBase",
  "Internet Information Services (IIS)",
  "Intersystems Cache",
  "Intranet Architecture",
  "Intranet Implementation",
  "io.js",
  "Ionic",
  "iOS",
  "iOS 7",
  "iOS Development",
  "iOS Jailbreaking",
  "iPad App Development",
  "iPhone App Development",
  "iPhone SDK",
  "IPMI",
  "IPsec",
  "Iptables",
  "IRC Server Administration",
  "iReport",
  "IronPython",
  "ISA Server",
  "Issue Tracking Systems",
  "iTextSharp",
  "J2ME",
  "J2SE",
  "JasperReports",
  "Java",
  "Java EE",
  "Java ME",
  "Java Remote Method Invocation (Java RMI)",
  "Java Servlets Development",
  "JavaFX",
  "Javascript",
  "JavaServer Faces (JSF)",
  "JAXB",
  "Jboss",
  "JBoss",
  "Seam",
  "JBPM",
  "JCL",
  "JDBC",
  "JDBC Programming",
  "JDeveloper",
  "Jellybean",
  "Jenkins",
  "JFC",
  "Jimdo",
  "Jinja2",
  "JMeter",
  "JMS",
  "JNCIA-Junos",
  "JNDI",
  "JomSocial Development",
  "Joomla",
  "Joomla Fabrik",
  "Joomla Migration",
  "Joomla Upgrade",
  "Joomla!",
  "JPA",
  "jQuery",
  "jQuery Mobile",
  "JSCapture",
  "Jsharp",
  "JSON",
  "JSP",
  "JSTL",
  "Juniper Routers",
  "JUnit",
  "Junos",
  "Kaltura",
  "Kentico CMS",
  "Kerberos",
  "Key Lime Pie",
  "Key/Value Stores",
  "Kindle App Development",
  "Kindle Fire",
  "Kindle Fire Apps",
  "KitKat",
  "KiXtart",
  "Knockout.js",
  "KnockoutJS",
  "koa.js",
  "Kohana",
  "Korn shell",
  "Kubernetes",
  "KVM",
  "KVM Switches",
  "KVM Virtualization",
  "LAMP Administration",
  "LAN Administration",
  "LAN Implementation",
  "LANDesk",
  "Laravel",
  "Laravel Framework",
  "Lasso",
  "Lawson",
  "Lazy.js",
  "LDAP",
  "LemonStand",
  "Leptonica",
  "LESS (stylesheet language)",
  "Level Design",
  "libcurl",
  "libGDX",
  "Liferay",
  "Lighttpd",
  "LimeJS",
  "LimeSurvey",
  "LinkedIn Development",
  "LINQ",
  "linq to entities",
  "linq to sql",
  "Linux",
  "LiquidPlanner",
  "Lisp",
  "Lithium",
  "Lithium Framework",
  "Live Chat Software",
  "Load Balancing",
  "Load testing",
  "LoadRunner",
  "Localization",
  "Log4j",
  "LogiXML",
  "LogMeIn Hamachi",
  "LogMeIn Rescue",
  "Lotus Approach",
  "Lua",
  "Lucene Search",
  "m0n0wall",
  "Mac OS",
  "Mac OS App Development",
  "Mac OSX Administration",
  "Machine Learning",
  "Maemo",
  "Mail Server Implementation",
  "MailEnable",
  "Make Build Script",
  "Mambo",
  "ManageEngine",
  "Mantis",
  "Manual Test Execution",
  "MAPI",
  "Mapinfo",
  "Mapr",
  "MapReduce",
  "MariaDB",
  "Mathematica",
  "Matlab",
  "McAfee ePolicy Orchestrator",
  "McAfee VirusScan",
  "MCP",
  "Mechanical Turk API",
  "MediaWiki",
  "Memcached",
  "Menu Design",
  "MerchantRun",
  "MerchantRun GlobalLink",
  "Mercurial",
  "Merise",
  "MetaTrader 4 (MT4)",
  "Meteor",
  "Metro",
  "Microsoft Access Administration",
  "Microsoft Access Programming",
  "Microsoft Active Directory",
  "Microsoft Business Intelligence Studio",
  "Microsoft Certified Information Technology Professional (MCITP)",
  "Microsoft Commerce Server",
  "Microsoft Dynamics Administration",
  "Microsoft Dynamics CRM",
  "Microsoft Dynamics Development",
  "Microsoft Dynamics ERP",
  "Microsoft Dynamics GP",
  "Microsoft Entity Framework",
  "Microsoft Exchange Server",
  "Microsoft Expression",
  "Microsoft Foundation Classes (MFC)",
  "Microsoft FrontPage",
  "Microsoft Hyper V",
  "Microsoft Hyper-V Server",
  "Microsoft Infopath",
  "Microsoft Kinect Development",
  "Microsoft Lync Server",
  "Microsoft Message Queue Server (MMSQ)",
  "Microsoft Office Live Web Design",
  "Microsoft Office SharePoint Server",
  "Microsoft Outlook Development",
  "Microsoft SCCM",
  "Microsoft SCVMM",
  "Microsoft Server",
  "Microsoft SharePoint Designer",
  "Microsoft Sharepoint Development",
  "Microsoft Silverlight",
  "Microsoft Small Business Server Administration",
  "Microsoft SQL CE",
  "Microsoft SQL Server Administration",
  "Microsoft SQL Server Notification Services",
  "Microsoft SQL Server Programming",
  "Microsoft SQL Server Service Broker",
  "Microsoft SQL SSAS",
  "Microsoft SQL SSRS",
  "Microsoft Transaction Server (MTS)",
  "Microsoft Virtual Server",
  "Microsoft Visual C++",
  "Microsoft Visual Studio",
  "Microsoft Visual Studio LightSwitch",
  "Microsoft Windows Azure",
  "Microsoft Windows Phone 7",
  "App Development",
  "Microsoft Windows Powershell",
  "Microsoft Windows Server",
  "Microsoft Windows Workflow Foundation",
  "MicroStrategy",
  "Mikrotik RouterBOARD",
  "Mikrotik RouterOS",
  "Minecraft",
  "Minitab",
  "MINIX",
  "Miva Merchant",
  "Mobile App Development",
  "Mobile App Testing",
  "Mobile Development Framework",
  "Mobile Programming",
  "Mocha",
  "Mockito",
  "Model View Controller (MVC)",
  "Modul8",
  "MODx",
  "MongoDB",
  "Mongrel",
  "Mono",
  "Moonfruit SiteMaker",
  "MooTools",
  "MovableType",
  "Mozenda Scraper",
  "MQL 4",
  "MS Access",
  "MS SQL Server",
  "MS-DOS Administration",
  "mtek",
  "Multi Router Traffic Grapher (MRTG)",
  "Multi-touch Hardware Development",
  "Multi-touch Hardware Programming",
  "Multiprotocol Label Switching (MPLS)",
  "Multithreaded Programming",
  "Munin",
  "MXML",
  "MySpace API",
  "MySQL",
  "MySQL Administration",
  "MySQL Programming",
  "n2cms",
  "n3-charts",
  "Nagios",
  "Natural Language Processing",
  "Neo4j",
  "NetBeans",
  "NetBSD",
  "Netezza",
  "NetSuite Administration",
  "NetSuite Development",
  "Nette",
  "Network Analysis",
  "Network Design",
  "Network Monitoring",
  "Network Pentesting",
  "Network Planning",
  "Neuro-linguistic programming",
  "NFS Administration",
  "NFS Implementation",
  "ngCore",
  "NHibernate",
  "NI Multisim",
  "Ning Development",
  "NodeJS",
  "node.js",
  "NopCommerce",
  "NoSQL",
  "NoSQL Couch",
  "Novell NetWare",
  "NServiceBus",
  "OAuth",
  "Object oriented design",
  "Object Oriented PHP",
  "Object Oriented Programming (OOP)",
  "Object Pascal",
  "Objective C",
  "Objective-C",
  "Objective-J",
  "OCaml",
  " OCR algorithms",
  "OCR Tesseract",
  "OCX",
  "ODBC",
  "oDesk API",
  "OGRE",
  "OLAP",
  "OLE",
  "OLE Automation",
  "OmniGraffle",
  "On-Page Optimization",
  "Online Transaction Processing (OLTP)",
  "OOPS",
  "ooVoo Development",
  "Open Cart",
  "OpenBravo PoS",
  "OpenBSD",
  "OpenCart",
  "OpenCL",
  "OpenCV",
  "OpenEMM",
  "OpenERP Administration",
  "OpenERP Development",
  "Openflow",
  "OpenGL ES",
  "OpenLayers",
  "OpenSIPS",
  "OpenSocial",
  "OpenStack",
  "openSUSE",
  "OpenTok Development",
  "OpenVBX",
  "OpenVMS",
  "OpenVPN",
  "OpenVZ",
  "OpenWrt",
  "OpenX",
  "Operating Systems Development",
  "Orace OBIEE Plus",
  "Oracle",
  "Oracle 10g Administration",
  "Oracle 10g Programming",
  "Oracle 11g Administration",
  "Oracle 11g Programming",
  "Oracle 12c Administration",
  "Oracle 12c Programming",
  "Oracle 9i Administration",
  "Oracle 9i Programming",
  "Oracle Administration",
  "Oracle Agile",
  "Oracle APEX",
  "Oracle Application Framework",
  "Oracle Application Server",
  "Oracle ATG Web Commerce",
  "Oracle BRM",
  "Oracle CRM On Demand",
  "Oracle Data Guard",
  "Oracle Database",
  "Oracle Database Administration",
  "Oracle Demantra",
  "Oracle E-Business Suite",
  "Oracle Endeca",
  "Oracle Enterprise Service Bus",
  "Oracle Financials Applications",
  "Oracle Forms",
  "Oracle Fusion Applications",
  "Oracle Fusion Middleware",
  "Oracle Global Trade Management",
  "Oracle Hyperion Planning",
  "Oracle Java EE",
  "Oracle JD Edwards EnterpriseOne",
  "Oracle Patching",
  "Oracle Peoplesoft Administration",
  "Oracle Peoplesoft Development",
  "Oracle Performance Tuning",
  "Oracle PL/SQL",
  "Oracle Policy Automation",
  "Oracle Primavera",
  "Oracle Programming",
  "Oracle Real Application Clusters (RAC)",
  "Oracle Reports",
  "Oracle RightNow",
  "Oracle Siebel",
  "Oracle SOA Suite",
  "Oracle Sun Ray",
  "Oracle Taleo",
  "Oracle Team Productivity Center",
  "Oracle Transportation Management",
  "Oracle Unified Method",
  "Oracle Upgrade",
  "Oracle User Productivity Kit",
  "Oracle WebLogic",
  "Orchard CMS",
  "ORM",
  "ORMLite  OS/2",
  "OSGi",
  "OSPF",
  "Palm OS",
  "Papervision3D",
  "Parallels Virtual Desktop",
  "Pascal",
  "Pattern recognition",
  "Payment Gateway Integration",
  "Payment Processing",
  "Paypal API",
  "PayPal Development",
  "Paypal Integration",
  "PBwiki",
  "PBworks Development",
  "PCAP",
  "PCI Compliance",
  "PEAR",
  "PeopleCode",
  "Perforce",
  "Performance testing",
  "Performance Tuning",
  "Perl",
  "Perl Catalyst",
  "Perl Mojolicious",
  "PerlDancer",
  "Pervasive Software",
  "PfSense",
  "PGP",
  "Phalcon",
  "PhantomJS",
  "Phing",
  "PhoneGap",
  "PHP",
  "PHP on TRAX",
  "PHP-Nuke",
  "PHP4",
  "PHPBB",
  "PHPDevShell",
  "PHPfox",
  "PHPixie",
  "phpMyAdmin",
  "phpMyDirectory",
  "PhpOpenbiz",
  "PICK MultiValue DB",
  "Pig",
  "PL/SQL",
  "Platform Migration",
  "Play Framework",
  "PLC Programming",
  "Pligg",
  "Plivo",
  "Plone",
  "PMDS",
  "Pocket PC",
  "Portfolio Performance Modeling",
  "Portlets",
  "POS Terminal Development",
  "Posterous",
  "Postfix SMTP Server",
  "PostgreSQL",
  "PostgreSQL Administration",
  "PostgreSQL Programming",
  "PostScript",
  "Power Builder",
  "PowerBuilder",
  "Prado",
  "PRADO PHP Framework",
  "Predictive Analytics",
  "PrimeFaces",
  "Private Clouds",
  "Processing",
  "ProcessWire",
  "ProcessWire CMS",
  "Product Management",
  "Progress.js",
  "Prolog",
  "Prototype",
  "Prototype Javascript Framework",
  "prototype.js",
  "PSD to MailChimp",
  "PSD to XHTML",
  "Pug (Jade)",
  "Punching",
  "Puppet Administration",
  "PureScript",
  "Pyjamas",
  "Pylons",
  "PyQt",
  "Pyro",
  "Python",
  "Python Numpy",
  "Python SciPy",
  "Q (Programming Language)",
  "QA Engineering",
  "QA Management",
  "QA Testing",
  "Qcodo",
  "QlikTech QlikView",
  "Qmail",
  "QNX",
  "Qooxdoo",
  "QPHP",
  "QT.io (cute)",
  "Quality of Service (Q-oS)",
  "Quantitative Analysis",
  "QuickBase",
  "QuickFIX",
  "R (Programming Language)",
  "R-Hadoop",
  "Rackspace",
  "Rackspace Cloud Servers",
  "Radiant CMS",
  "RADIUS",
  "RAID Administration",
  "Raphael JS",
  "Rapid Miner",
  "Raspberry Pi",
  "Rational Unified Process (RUP)",
  "Razor Template Engine",
  "React.js",
  "React",
  "Real Estate IDX",
  "Real time stream processing",
  "REALbasic",
  "Receipt Parsing",
  "Recommender Systems",
  "Red Hat",
  "Red Hat Administration",
  "Red Hat Certified Engineer (RHCE)",
  "Red Hat Enterprise Linux (RHEL)",
  "Red5",
  "Redis",
  "Redmine",
  "Refinery CMS",
  "Regression Testing",
  "Regular Expressions",
  "Relational Databases",
  "Remoting",
  "Requirement Management",
  "Requirements analysis",
  "Resin",
  "Resource Description Framework (RDF)",
  "Respond CMS",
  "Responsive Web Design",
  "REST",
  "REST API",
  "RETS",
  "RFID",
  "Rhino Service Bus",
  "Rhodes Framework",
  "Richfaces",
  "RightScale",
  "Riverbed",
  "Robot Framework",
  "Rocket Engine",
  "Root Cause Analysis",
  "RPG (OS/400)",
  "RPG Development",
  "RSpec",
  "RSS",
  "RTL",
  "RTLinux",
  "RTML",
  "Ruby",
  "Ruby On Rails",
  "RulersGuide.js",
  "S (Statistical Programming Language)",
  "SaaS",
  "Sabre",
  "Salesforce Apex",
  "Salesforce App Development",
  "Samba",
  "SAP ABAP",
  "SAP AG",
  "SAP Analysis",
  "SAP BASIS",
  "SAP BSP",
  "SAP BusinessOne",
  "SAP CRM",
  "SAP ERP",
  "SAP ERP HCM",
  "SAP Hana",
  "SAP Logistics Execution",
  "SAP Materials Management",
  "SAP NetWeaver",
  "SAP Programming",
  "SAP SD",
  "SAP Solution Manager",
  "SAP Sybase Adaptive Server Enterprise",
  "SAP Warehouse Management",
  "SAP Web Dynpro",
  "SAS",
  "SAS Business Analytics",
  "Sass",
  "Savant3",
  "SCADA",
  "Scala",
  "Scalable analytics",
  "Scalable transaction processing",
  "Scalr",
  "Scheme",
  "SCORM",
  "Scrapy",
  "Script.aculo.us",
  "ScriptCase",
  "Scripting",
  "Scripts & Utilities",
  "ScrollReveal.js",
  "ScrumWorks",
  "Seagull",
  "Section 508 Compliance",
  "Seen.js",
  "Selenium",
  "Selenium WebDriver",
  "Sencha",
  "Sencha GXT",
  "Sendmail",
  "Sentiment analysis",
  "SEO Backlinking",
  "Serenic Navigator",
  "Serial Port Interfacing",
  "Serialization",
  "Servlet",
  "Servoy",
  "Shepherd.js",
  "Shine.js",
  "ShiVa3D",
  "SHOUTcast",
  "Shozu",
  "Siebel Development",
  "SigmaPlot",
  "Silex",
  "Silex Framework",
  "SilverStripe",
  "SimpleDB",
  "Simulink",
  "Sinatra Framework",
  "SIP",
  "SiteBuildIt",
  "Sitecore",
  "Sitefinity CMS",
  "SkaDate",
  "Skype Development",
  "Slackware Linux",
  "Slim",
  "Smalltalk",
  "smart Contract",
  "SmartFoxServer",
  "Smarty",
  "Smoothie Charts",
  "SMPP",
  "SMS",
  "SMS Gateway",
  "SMTP",
  "SNMP",
  "Snort",
  "SOAP",
  "SoapUI",
  "Social bookmarking",
  "Social Networking Development",
  "SocialEngine",
  "Socket IO",
  "Socket Programming",
  "Software Configuration Management",
  "Software Debugging",
  "Software Defined Networking (SDN)",
  "Software Licensing",
  "Software optimization",
  "Solaris",
  "Solaris Administration",
  "SpamAssassin",
  "Sphinx",
  "Splunk",
  "Spree",
  "Spring Framework",
  "Spring Security",
  "SQA",
  "SQL",
  "SQL Azure",
  "SQL CLR",
  "SQL Programming",
  "SQL Server Integration Services (SSIS)",
  "SQLAlchemy",
  "SQLite",
  "SQLite Administration",
  "SQLite Programming",
  "Sqoop",
  "SQR",
  "Squarespace",
  "Squid",
  "SSH",
  "SSI",
  "SSL",
  "Stata",
  "Statistical Computing",
  "Sticker.js",
  "Stored Procedure Development",
  "Stream Processing",
  "Stripe",
  "Stripe API",
  "Structured Cabling",
  "Subversion",
  "SugarCRM Development",
  "Swift (Programming Language)",
  "Swing",
  "SWiSH Max",
  "Switchery.js",
  "SWT",
  " Sybase Programming",
  "Symbian",
  "Symbian Development",
  "Symfony",
  "Symfony2",
  "Syncsort",
  "System Analysis",
  "System Automation",
  "System Programming",
  "Systems Development",
  "Tableau Software",
  "Talend Open Studio",
  "TaoBao API",
  "Tapestry",
  "TAPI",
  "Tastypie",
  "Taxonomy",
  "Tcl",
  "Tcl/Tk",
  "Team Foundation Server",
  "TeamViewer",
  "Telerik",
  "Telerik Sitefinity CMS",
  "Teradata",
  "Tesseract",
  "Test Automation",
  "Test Case Design",
  "Test Driven Development",
  "TestComplete",
  "Testing Framework",
  "TestLink",
  "TestLodge",
  "Testopia",
  "TestStand",
  "Textpattern",
  "Titanium",
  "Tizen",
  "Tk",
  "Tornado",
  "Torque Game Engine",
  "Tortoise SVN",
  "Trac",
  "Transact-SQL",
  "Transaction Processing",
  "Triakis VSIL",
  "Trixbox",
  "Tropo",
  "TurboGears",
  "Twig",
  "Twilio API",
  "Twitter API",
  "Twitter Bootstrap",
  "Two-factor authentication (2FA)",
  "Type Rendering Mix",
  "Typepad",
  "TypeScript",
  "TYPO3",
  "TYPO3 Flow PHP",
  "TYPO3 PHP",
  "Ubercart",
  "Ubuntu",
  "Umbraco",
  "UML",
  "Unified Threat Management",
  "Unify",
  "Unify Corporation",
  "Unify SQLBase",
  "Unit Testing",
  "Unity",
  "Unix",
  "Unix Shell",
  "Unix System Administration",
  "Unreal Engine",
  "UnrealScript",
  "User acceptance testing",
  "uvCharts",
  "Vaadin Framework",
  "Valgrind",
  "Varnish Cache",
  "VB.NET",
  "VBA",
  "VBScript",
  "Veeam",
  "Velocity Template Engine",
  "Vendor Management Systems",
  "Version Control",
  "Vertica",
  "VHDL",
  "VICIDIAL",
  "Video Streaming",
  "Vim",
  "Virtual Currency",
  "Virtual Machine",
  "Virtualization",
  "Virtuoso",
  "Virus Removal",
  "Vis.js",
  " Visual Basic",
  "Visual Dataflex",
  "Visual Foxpro",
  "Visualforce",
  "Visualization",
  "Vizrt",
  "VKontakte API",
  "VMware Administration",
  "VMware ESX Server",
  "VoiceXML",
  "VOIP Administration",
  "VOIP Software",
  "Voldemort",
  "VSS",
  "vtiger Adminstration",
  "vtiger Development",
  "VTK",
  "Vugen Scripting",
  "Vulnerability Assessment",
  "VxWorks",
  "W3C Widget API",
  "WACT",
  "WAMP",
  "WAN",
  "WAN Optimization",
  "WASP",
  "WEB3",
  "Web3.js",
  "Web Crawling",
  "Web Host Manager",
  "Web Programming",
  "Web Services",
  "Web Services Development",
  "Web Testing",
  "web2py",
  "WebApp Pentesting",
  "Webeeh",
  "webERP",
  "WebGL",
  "WebHost Manager (WHM)",
  "Webisode Presentation",
  "Webisode Production",
  "WebOS",
  "Website Baker",
  "Website Prototyping",
  "Website Wireframing",
  "Weebly",
  "Weka",
  "WHMCS Development",
  "Wicket",
  "Win32 App Development",
  "WinAutomation",
  "WinDev",
  "WinDev Mobile",
  "Windows",
  "Windows 10",
  "Windows 2000",
  "Windows 7",
  "Windows 7 Administration",
  "Windows 8",
  "Windows 8 Administration",
  "Windows 8 App Development",
  "Windows 98",
  "Windows Administration",
  "Windows API",
  "Windows App Development",
  "Windows CE",
  "Windows Communication Foundation (WCF)",
  "Windows Desktop",
  "Windows Forms Development",
  "Windows Mobile",
  "Windows NT",
  "Windows NT Administration",
  "Windows Phone",
  "Windows Presentation Foundation (WPF)",
  "Windows Server",
  "Windows Server 2003",
  "Windows Server 2008",
  "Windows Server 2012",
  "Windows Vista",
  "Windows XP",
  "Windows XP Administration",
  "Winjs",
  "WinRunner",
  "Winsock",
  "Wireless Security",
  "Wix",
  "WML Script",
  "WordPress",
  "WordPress e-Commerce",
  "WordPress Plugin",
  "WordPress Template",
  "Worketc",
  "Worldspan",
  "Wow.js",
  "Wowza Media Server",
  "WPF",
  "WxWidgets",
  "X-Cart",
  "X86 assembly language",
  "x86/x64 Assembler",
  "Xamarin",
  "Xamarin SDK",
  "XAML",
  "XAMPP",
  "Xbox",
  "Xen Cloud Platform",
  "Xen Hypervisor",
  "XenForo",
  "XHTML",
  "Xilinx",
  "Xlinesoft PHPRunner",
  "XML",
  "xml Web Services",
  "XML-RPC",
  "XMPP",
  "XOOPS",
  "XPath",
  "XQuery",
  "XSD",
  "XSL",
  "XSLT",
  "XUL",
  "Yahoo Developer Skills",
  "Yahoo! Merchant Solutions",
  "Yahoo! Query Language",
  "Yahoo! Store",
  "YahooUI",
  " YAML",
  "Yii",
  "Yii2",
  "Yola",
  "YouTube Development",
  " YUI Library",
  "Zabbix",
  "Zend Framework",
  "Zend Studio",
  "Zennolab ZennoPoster",
  "Zikula",
  "Zimbra Administration",
  "Zimbra Development",
  "ZingChart",
  "ZK",
  "Zoho Creator",
  "Zoho Creator Programming",
  "Zoho CRM",
  "Zoomla",
  "ZooP",
  "Zope",
];

const infrastructure = [
  "Active Directory",
  "Amazon Web Services",
  "Ansible",
  "Apache",
  "Apache Solr",
  "Asterisk",
  "Azure",
  "Bitcoin",
  "Blog Install",
  "Business Catalyst",
  "CasperJS",
  "Celery",
  "Chat Bot",
  "Chef",
  "Chordiant",
  " Cloud Computing",
  "Cold Fusion",
  "Computer Security",
  "CRE Loaded",
  "CS-Cart",
  "CubeCart",
  "DNS",
  "Docker",
  "Dockerfile",
  "DotNetNuke",
  "Dynamics",
  "eCommerce",
  "edX",
  "eLearning",
  "Fabric",
  "Facebook",
  "Flowdock",
  "Forum Software",
  "Google Analytics",
  "Google App Engine",
  "Google Cloud Platform",
  "Google Earth",
  "Google Plus",
  "Hadoop",
  "HP OpenView",
  "IBM Tivoli",
  "IIS",
  "Interspire",
  "J2EE",
  "Jabber",
  "Linkedin",
  "Lotus Notes",
  "Magento",
  "Metatrader",
  "Microsoft Exchange",
  "Moodle",
  "Myspace",
  "Nginx",
  "Ning",
  "OSCommerce",
  "Parallels Automation",
  "Parallels Desktop",
  "Pentaho",
  "Pinterest",
  "Plesk",
  "Prestashop",
  "Protoshare",
  "Puppet",
  "QlikView",
  "Reddit",
  "SAP",
  "Script Install",
  "Sharepoint",
  "Shell Script",
  "Shopify",
  "Shopping Carts",
  "Siebel",
  "SolusVM",
  "SugarCRM",
  "System Administration",
  "Telegram",
  "Trading Bot",
  "Tumblr",
  "Twitter",
  "vBulletin",
  "Virtuemart",
  "Virtuozzo",
  "VoIP",
  "Volusion",
  "VPS",
  "vTiger",
  "Web Hosting",
  "Web Security",
  "webMethods",
  "Website Management",
  "WHMCS",
  "Woocommerce",
  "YouTube",
  "Zen Cart",
  "Zoho",
];

const writing = [
  "Academic Writing",
  "Adobe Content Server",
  "Adobe InCopy",
  "Adobe PDF",
  "Adobe RoboHelp",
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Amharic Language",
  "AP Style Writing",
  "Appian BPM Suite",
  "Apple iBooks",
  "Arabic",
  "Armenian",
  "Article curation",
  "Article Rewriting",
  "Article Spinning",
  "Article Writing",
  "Articles",
  "Author-It",
  "Azerbaijani",
  "Basque",
  "Bengali",
  "Biography Writing",
  "Blog Commenting",
  "Blog Writing",
  "Blogging",
  "Book Writing",
  "Bosnian,",
  "BuildMyRank Writing",
  "Bulgarian",
  "Business Proposal Writing",
  "Business Writing",
  "Cantonese",
  "Cartography & Maps",
  "Catalan",
  "Catch Phrases",
  "Cherokee",
  "Children's Writing",
  "Chinese",
  "Chinese (Hong Kong)",
  "Comic Writing",
  "Content Management",
  "Content Marketing",
  "Content Writing",
  "Copy Editing",
  "Copywriting",
  "Cover Letter Writing",
  "Creative Writing",
  "Croatian",
  "Curriculum Development",
  "Czech",
  "Danish",
  "Data Entry",
  "Distance Education",
  "DocBook",
  "Document review",
  "Dutch",
  " eBook Design",
  "ebook Writing",
  "eBooks",
  "Economic Analysis",
  "Editing",
  "Editorial Writing",
  "English (AU)",
  "English (UK)",
  "English (US)",
  "English Grammar",
  "English Proofreading",
  "English Punctuation",
  "English Spelling",
  "English Tutoring",
  "ePub",
  "Erotica Writing",
  "Essay Writing",
  "Estonian",
  "FAAC",
  "Fact Checking",
  "Feature Writing",
  "Fiction Writing",
  "Filipino",
  "Filipino - Visayan Dialect",
  "Film Criticism",
  "Film Review",
  "Final Draft",
  "Financial Writing",
  "Finnish",
  "Forum Posting",
  "French",
  "French (Canada)",
  "Galician",
  "Georgian",
  "German",
  "Ghostwriting",
  "Grant Writing",
  "Greek  Gujarati",
  "Haitian Creole",
  "Hebrew",
  "Hindi",
  "Humor Writing",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Investigative Reporting",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "JOnAS",
  "Journalism Writing",
  "Kannada",
  "Khmer",
  "Korean",
  "Kyrgyz",
  "Lao",
  "LaTeX",
  "Latvian",
  "Legal Writing",
  "Lesson Plan Writing",
  "Letter Writing",
  "Lingo",
  "Linkvana",
  "Literature Review",
  "Lithuanian",
  "Lyrics Writing",
  "Macedonian",
  "MadCap Software",
  "Malay",
  "Malayalam",
  "Malaysian",
  "Mandarin",
  "Marathi",
  "Medical Writing",
  "Microsoft Word",
  "MindTouch",
  "Molecule Editors",
  "Mongolian",
  "Morae",
  "Nepali",
  "News Writing Style",
  "Newsletter Writing",
  "Non-Fiction Writing",
  "Norwegian",
  "Online Writing",
  "Pashto",
  "Persian",
  "Poetry",
  "Polish",
  "Portuguese",
  "Portuguese (Brazil and Portugal)",
  "Press Release Writing",
  "Product Descriptions",
  "Proofreading",
  "Proposal Writing",
  "Punjabi",
  "Pure Data",
  "Report Writing",
  "Research Papers",
  "Resume Writing",
  "Reviews",
  "Romanian",
  "Romantic Writing",
  "RPG Writing",
  "Russian",
  "Russian Language",
  "Sales Letters",
  "Sales Writing",
  "Satire",
  "Scenario Planning",
  "Scientific Writing",
  "Screenwriting",
  "Script Writing",
  "SDL Passolo",
  "SDL Trados",
  "SDLX",
  "Serbian",
  "Short Story Writing",
  "Simplified Chinese",
  "Sinhala",
  "Slang-style Writing",
  "Slogans",
  "Slovak",
  "Slovakian",
  "Slovenian",
  "Software Documentation",
  "Spanish",
  "Spanish (Latin America)",
  "Speech Writing",
  "Stakeholder Management",
  "Stenography",
  "String Manipulation",
  "Subtitling",
  "Swahili",
  "Swedish",
  "Synopsis Writing",
  "Tagalog",
  "Tamali",
  "Tamil",
  "Teaching English",
  "Technical Analysis",
  "Technical Documentation",
  "Technical Editing",
  "Technical Writing",
  "Telugu",
  "Thai",
  "Traditional Chinese",
  "Transcreation",
  "Transcription (audio to text)",
  "Translation",
  "Translation Afrikaans English",
  "Translation Albanian English",
  "Translation Armenian English",
  "Translation Belarusian English",
  "Translation Bengali English",
  "Translation Bulgarian English",
  "Translation Catalan English",
  " Translation Croatian English",
  "Translation Czech English",
  "Translation Danish English",
  "Translation English Afrikaans",
  "Translation English Albanian",
  "Translation English Armenian",
  "Translation English Belariusan",
  "Translation English Bengali",
  "Translation English Bulgarian",
  "Translation English Catalan",
  "Translation English Croatian",
  "Translation English Czech",
  "Translation English Danish",
  "Translation English Estonian",
  "Translation English Filipino",
  "Translation English Finnish",
  "Translation English Galician",
  "Translation English Georgian",
  "Translation English German",
  "Translation English Greek",
  "Translation English Gujarati",
  "Translation English Haitian Creole",
  "Translation English Hebrew",
  "Translation English Hindi",
  "Translation English Hungarian",
  "Translation English Icelandic",
  "Translation English Indonesian",
  "Translation English Irish",
  "Translation English Japanese",
  "Translation English Kannada",
  "Translation English Kyrgyz",
  "Translation English Latin",
  "Translation English Latvian",
  "Translation English Lithuanian",
  "Translation English Macedonian",
  "Translation English Malay",
  "Translation English Maltese",
  "Translation English Mandarin (Chinese)",
  "Translation English Marathi",
  "Translation English Norwegian",
  "Translation English Persian",
  "Translation English Romanian",
  "Translation English Russian",
  "Translation English Serbian",
  "Translation English Slovak",
  "Translation English Slovenian",
  "Translation English Spanish",
  "Translation English Swahili",
  "Translation English Swedish",
  "Translation English Tamil",
  "Translation English Telugu",
  "Translation English Thai",
  "Translation English Turkish",
  "Translation English Ukrainian",
  "Translation English Urdu",
  "Translation English Vietnamese",
  "Translation English Welsh",
  "Translation English Yiddish",
  "Translation Estonian English",
  "Translation Filipino English",
  " Translation Finnish English",
  "Translation French German",
  "Translation French Spanish",
  "Translation Galician English",
  "Translation Georgian English",
  "Translation German English",
  "Translation German French",
  "Translation German Polish",
  "Translation Greek English",
  "Translation Gujarati English",
  "Translation Haitian Creole English",
  "Translation Hebrew English",
  "Translation Hindi English",
  "Translation Hungarian English",
  "Translation Icelandic English",
  "Translation Indonesian English",
  "Translation Irish English",
  "Translation Japanese English",
  "Translation Kannada English",
  "Translation Latin English",
  "Translation Latvian English",
  "Translation Lithuanian English",
  "Translation Macedonian English",
  "Translation Malay English",
  "Translation Maltese English",
  "Translation Mandarin (Chinese) English",
  "Translation Marathi English",
  "Translation Norwegian English",
  "Translation Persian English",
  "Translation Polish German",
  "Translation Romanian English",
  "Translation Russian English",
  "Translation Serbian English",
  "Translation Slovak English",
  "Translation Slovenian English",
  "Translation Spanish English",
  "Translation Spanish French",
  "Translation Swahili English",
  "Translation Swedish English",
  "Translation Tamil English",
  "Translation Telugu English",
  "Translation Thai English",
  "Translation Turkish English",
  "Translation Ukrainian English",
  "Translation Urdu English",
  "Translation Vietnamese English",
  "Translation Welsh English",
  "Translation Yiddish English",
  "Travel Writing",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "User's",
  "Guide Writing",
  "Vietnamese",
  "Welsh",
  "White Paper Writing",
  "WIKI",
  "Wikipedia",
  "Word Processing",
  "WordPerfect",
  "Writing",
  "Wu",
  "Zulu",
];

const allSkills = [
  ...adminSupport,
  ...apiSiteFramework,
  ...designMultimedia,
  ...hardwareEngineering,
  ...legalities,
  ...management,
  ...marketing,
  ...methodology,
  ...mobilePhone,
  ...networkSecurity,
  ...programmingIt,
  ...infrastructure,
  ...writing,
];

export {
  allSkills,
  adminSupport,
  apiSiteFramework,
  designMultimedia,
  hardwareEngineering,
  legalities,
  management,
  marketing,
  methodology,
  mobilePhone,
  networkSecurity,
  programmingIt,
  infrastructure,
  writing,
};
